### ISSUE TITLE
내사시...

### ISSUE THREAD

**Issue by ioritree** [PowerHouseMan/ComfyUI-AdvancedLivePortrait#11]
내사시 효과를 얻을 수 없는 것 같습니다.

**Comment by PowerHouseMan** [comment]
ㄷㄷㄷ.... 모델이 일반적인 데이터로 학습된거라 양쪽다 하려고 하면 이미지가 많이 왜곡 되네요. 보통 일반적인 병적인 내사시는 한쪽인 경우가 대다수라 한쪽 내사시는 가능하지만... 음... 양쪽을 원하시는 거겠죠? 사진을 반씩 잘라 붙이는 방법 밖에는 생각이 나지 않네요...
![제목 없음](https://github.com/user-attachments/assets/8cd74571-8f4b-462c-a8a1-55e286b5e1cf)

**Comment by jiangpeiming** [comment]
https://github.com/KwaiVGI/LivePortrait/issues/154
I hope the code can be updated soon.
