### ISSUE TITLE
How to play with Comfyui like the video in your introduction?

### ISSUE THREAD

**Issue by Young-Chin** [PowerHouseMan/ComfyUI-AdvancedLivePortrait#15]
Hi!

It's great work to edit the expression with LivePortrait instead of driving video only.

But what really interested me is the real-time editing expression as shown in the introduction. Would you tell me how to do that in ComfyUI?

Thx~

**Comment by PowerHouseMan** [comment]
Check Extra options under the Queue Prompt button and check Auto Queue

**Comment by Young-Chin** [comment]
Awesome! Got a new tip~hhhhh

**Comment by Miao-WangHao** [comment]
> Extra options under the Queue Prompt button and check Auto Queue

3060显卡也可以这样吗
