### ISSUE TITLE
Unable to perform video-to-video generation.

### ISSUE THREAD

**Issue by 0002kgHg** [PowerHouseMan/ComfyUI-AdvancedLivePortrait#18]
I tried to enhance the expression using the Expression Editor after face-swapping the same character (as the expression becomes quite stiff after using Reactor for face-swapping). However, this node seems unable to generate images in batches and can only output a single image at a time. This prevents me from directly using the meta batch for batch processing, forcing me to use a more complex method of splitting and generating images individually, which is very tedious.

[https://prnt.sc/vfAhYNr4ALzJ](url)

**Comment by PowerHouseMan** [comment]
Use AdvancedLivePortrait node. Read readme. See workflow2. You can make it work with vid2vid.
