### ISSUE TITLE
How do you quantify face expressions and implicit lmks？

### ISSUE THREAD

**Issue by jiangchh1** [PowerHouseMan/ComfyUI-AdvancedLivePortrait#19]
Amazing work！
Can you plz tell me how to quantify face expressions and implicit lmks.  I wonder if there are other expressions that can be expressed like this

**Comment by PowerHouseMan** [comment]
https://github.com/PowerHouseMan/ComfyUI-AdvancedLivePortrait/issues/4

**Comment by jiangchh1** [comment]
ty
