### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by 40740** [PowerHouseMan/ComfyUI-AdvancedLivePortrait#2]
Thank you, is the model the same as the original LivePortrait? Can we modify the model intersection to be the same as the LivePortrait path, so that there is no need to download the model again.

**Comment by 40740** [comment]
You can refer to https://github.com/kijai/ComfyUI-LivePortraitKJ
The texture of the mask for this project would be very perfect.

**Comment by PowerHouseMan** [comment]
The model in my project is the original model.
The model in ComfyUI-LivePortraitKJ is not the original, this is a converted model.
If you already have the converted model, I will update it so that you can use it.

**Comment by PowerHouseMan** [comment]
You can now use the converted model.

**Comment by 40740** [comment]
> 您现在可以使用转换后的模型。

Wow, thank you very much. May I ask if it's possible to add a feature like the mask in ComfyUI-LivePortraitKJ? This would allow the use of different sizes while still obtaining images of the same size. Thanks again for your work. It's a very good idea.
