### ISSUE TITLE
我不知道为什么会这样，明明没有放错位置

### ISSUE THREAD

**Issue by JioJe** [PowerHouseMan/ComfyUI-AdvancedLivePortrait#3]
![image](https://github.com/user-attachments/assets/f654cda6-6923-4f9e-b722-b46a5ae7e422)
![image](https://github.com/user-attachments/assets/85e0a17a-190a-40ac-b9b5-dc4f5581ada1)

**Comment by PowerHouseMan** [comment]
liveportait -> liveportrait
