### ISSUE TITLE
Video Facial Expression Editing + Face Tracking?

### ISSUE THREAD

**Issue by Zsnack** [PowerHouseMan/ComfyUI-AdvancedLivePortrait#30]
Thanks for the great work you've done with this so far! I was able to figure out how to use facial expression editing for video sources, but one of the issues as pointed out by another user is that the face crop region is taken only from the first frame of the video and does not work properly if the face in the video source moves out of that initial area. Would it be possible to eventually add some sort of facial tracking in the future for the source video for more robust results?

**Comment by PowerHouseMan** [comment]
It has been updated.

**Comment by Zsnack** [comment]
Wow, that was fast! Thank you!
