### ISSUE TITLE
How to find smile and other ratios?

### ISSUE THREAD

**Issue by harisreedhar** [PowerHouseMan/ComfyUI-AdvancedLivePortrait#4]
How do you find these ratios?
https://github.com/PowerHouseMan/ComfyUI-AdvancedLivePortrait/blob/750527cfc43d74896b375776b270ff497e39dd07/nodes.py#L204-L211

**Comment by PowerHouseMan** [comment]
To find the value of the smile, I looked for commonalities in smiling pictures.

**Comment by harisreedhar** [comment]
Awesome thanks man! Great project!
