### ISSUE TITLE
Instructions To Install Using ComfyUI Manager on Windows 11

### ISSUE THREAD

**Issue by MarsEverythingTech** [PowerHouseMan/ComfyUI-AdvancedLivePortrait#5]
Hello,

I was reading the installation for the repo and was wondering if I could install it by using ComfyUI Manager using Install from URL option instead of running the bat file inside the custom nodes folder. And if there are any other steps required, could you please guide me through them all? 

Thanks in advance

**Comment by PowerHouseMan** [comment]
Today it is registered in ComfyUI Manager. Everything will be installed automatically.

**Comment by MarsEverythingTech** [comment]
> Today it is registered in ComfyUI Manager. Everything will be installed automatically.

Hello, 

I installed it using the Manager, however, I am getting this error when dragging the workflow1_basic.json file into ComfyUI:

When loading the graph, the following node types were not found:
VHS_LoadVideo
VHS_VideoCombine
Nodes that have failed to load will show as red on the graph.

**Comment by PowerHouseMan** [comment]
Search for 'ComfyUI-VideoHelperSuite' in the manager and download it.
Then the red node becomes normal.

In the right menu of comfyUI, check 'Extra options' and check 'Auto Queue'.
Real-time transformation requires high computing power. My computer is RTX4090.

**Comment by MarsEverythingTech** [comment]
> Search for 'ComfyUI-VideoHelperSuite' in the manager and download it.
> 
> Then the red node becomes normal.
> 
> 
> 
> In the right menu of comfyUI, check 'Extra options' and check 'Auto Queue'.
> 
> Real-time transformation requires high computing power. My computer is RTX4090. 

Alright, thanks! I will follow the steps mentioned and will update you? 
Could you please also provide me the workflow of the demo video as well?
I have RTX 3070 Ti

**Comment by PowerHouseMan** [comment]
Just connect two nodes, a Load Image node and an Expression Editor node.
